[role="pagenumrestart"]
[[intro_what_is_the_lightning_network]]
== 简介


欢迎学习 _精通闪电网络_!



((("Lightning Network (generally)", seealso="innovations in Lightning", id="ix_01_introduction-asciidoc0", range="startofrange")))闪电网络（通常缩写为 LN）正在改变人们在线交换价值的方式，这是比特币历史上最令人兴奋的进步之一。
截至2021年，闪电网络仍处于起步阶段。 闪电网络是一种以智能且无感知的方式使用比特币的协议。 它是比特币之上的二层技术。



闪电网络的概念于 2015 年提出，并于 2018 年首次实施。截至 2021 年，我们才刚刚开始看到闪电网络为比特币提供的机会，包括改善隐私、速度和规模。
借助闪电网络的核心知识，您可以帮助塑造网络的未来，同时也为自己在行业里创造机会。



我们假设您已经对比特币有一些基本知识。但如果没有，请不要担心——我们将在 <<bitcoin_fundamentals_review>> 中解释最重要的比特币概念，即理解闪电网络必须了解的那些概念。 如果您想了解有关比特币的更多信息，您可以阅读 Andreas M. Antonopoulos (O'Reilly) 的《精通比特币》(第2版)，可在 https://github.com/bitcoinbook/bitcoinbook[免费在线阅读]。



虽然本书的大部分内容是为程序员编写的，但前几章的编写目的是让任何人都可以轻松理解，无论技术经验如何。 在本章中，我们将从一些术语开始，然后讨论信任及其在这些系统中的应用，最后我们将讨论闪电网络的历史和未来。 让我们开始吧。


=== 闪电网络基础概念



((("Lightning Network (generally)","basic concepts", id="ix_01_introduction-asciidoc1", range="startofrange")))当我们探索闪电网络的实际工作原理时，我们会遇到一些技术术语，起初可能会让您感到疑惑。虽然所有这些概念和术语，都将在我们接下来的章节中，给出详细的解释并在词汇表中进行定义，但现在厘清一些基本定义，将使接下来两章中的概念更容易理解。 如果您还不理解这些定义中的所有词汇，其实那没关系。 随着您阅读的加深，您会了解更多。


区块链:: ((("blockchain","defined")))由计算机网络生成的分布式交易账本。 例如，比特币是一个产生区块链的系统。闪电网络本身不是区块链，也不会产生区块链。它是一个依赖于现有外部区块链来保证其安全性的网络。


数字签名:: ((("digital signatures")))数字签名是一种用于验证数字消息或文档真实性的数学方案。 有效的数字签名使接收者有理由相信该消息是由已知的发件人创建的，发件人不能否认已发送该消息，并且该消息在传输过程中未被更改。


哈希函数:: ((("hash function, defined")))密码散列函数是一种数学算法，它将任意大小的数据映射到固定大小的位串（散列），并被设计为单向函数，即无法反向计算的函数。


节点:: ((("node, defined")))即参与网络的计算机。 闪电节点是参与闪电网络的计算机。 比特币节点是参与比特币网络的计算机。 通常，LN 用户将同时运行闪电节点和比特币节点。


链上行为 vs 链下行为:: ((("on-chain payment","defined")))如果付款被记录为比特币（或其他）区块链上的交易，则付款是 _链上_ 的行为。((("off-chain payment")))通过闪电节点之间的支付渠道发送的支付，在底层区块链中不可见，称为 _链下_ 支付。 通常在闪电网络中，唯一的链上交易是用于打开和关闭闪电支付通道的交易。 另外，存在第三种类型的通道修改交易(称为拼接)，可用于添加/删除通道中承诺的资金数量。


支付:: ((("payment","defined")))当在闪电网络上交换价值时，我们将其称为“支付”，而不是比特币区块链上的“交易”。


支付通道:: ((("payment channel", seealso="channel entries")))闪电网络上两个节点之间的“财务关系”，通常由多重签名的比特币交易实现，以此保证在两个闪电网络节点之间共享对比特币的控制权。


路由 vs 发送:: ((("routing","sending versus")))((("sending, routing versus")))与通过向所有人广播交易来“发送”交易的比特币不同，闪电网络是一个路由网络。它的支付，通过一个或多个支付渠道“路由”，遵循从发送者到接收者的 _路径_ 。


交易:: ((("transaction, defined"))) 交易是一种数据结构，该数据结构记录了对某些资金（例如某些比特币）的控制权转移的。闪电网络依靠比特币交易（或其他区块链的交易）来跟踪资金控制。


以上这些概念以及其他概念的更详细定义可以在 <<glossary>> 章节中进一步学习了解。 在本书中，我们将解释这些概念的含义以及这些技术的实际工作原理。



[TIP]
====
在本书中，您会看到首字母大写的“比特币”，它指的是 _比特币系统_，是一个专有名词。 您还将看到带有小写 _b_ 的“比特币”，表示货币单位。 每个比特币进一步细分为 1 亿个单位，每个单位称为“satoshi”（单数）或“satoshis”（复数）。
====


现在您已经熟悉了这些基本术语，让我们转向一个您已经熟悉的概念：信任。

=== Trust in Decentralized Networks

=== 分布式网络中的信任


((("Lightning Network (generally)","trust in decentralized networks")))((("trustless systems","trust in decentralized networks")))你会经常听到人们称比特币和闪电网络“免信任”。乍一看，这令人困惑。毕竟，信任不是一件好事吗？银行甚至在他们的名字中使用它！一个“去信任”的系统，一个缺乏信任的系统，难道不是一件坏事吗？


使用“免信任”一词，旨在传达该系统具备这样一种能力，即无需信任系统中其他参与者的操作。 在像比特币这样的去中心化系统中，您可以选择与您信任的人进行交易。 但是，即使您不信任交易中的另一方，该系统也可以确保您不会被欺骗。 在“免信任”系统中，信任是“尽量”具备的属性，而不是必备的属性。


与银行等传统系统相比，您必须信任第三方，因为它控制着您的资金。 如果银行违反了您的信任，您也许可以向监管机构或法院寻求一些追索权，但要付出巨大的时间、金钱和精力。


免信任并不意味着没有信任。这意味着信任不是所有交易的必要先决条件，您甚至可以与您不信任的人进行交易，因为系统可以防止作弊。


在我们了解闪电网络的工作原理之前，了解比特币、闪电网络和其他此类系统的一个基本概念非常重要，我们称这个概念为“公平协议”。 公平协议是一种在参与者之间实现公平结果的方法，参与者不需要相互信任，也不需要中央权威，它是比特币等去中心化系统的支柱。


=== 无中央权威的公平

((("fairness, ensuring")))((("Lightning Network (generally)","fairness without central authority")))当人们有相互竞争的利益时，他们如何建立足够的信任来进行一些合作或交易行为？ 这个问题的答案，来自于经济学、社会学、行为心理学和数学等几个自然科学和人文科学的核心。 其中一些学科给我们的“软”答案取决于声誉、公平、道德甚至宗教等概念。其他学科给我们的具体答案仅取决于这些互动的参与者将以他们的自身利益为主要目标的理性行为这一假设。


从广义上讲，有几种方法可以确保可能具有竞争利益的个人之间的互动结果公平：


信任必备:: 由于之前的互动、声誉或家庭关系，您只与您已经信任的人互动。 这在小范围内非常有效，特别是在家庭和小团体中，它是合作行为的最常见基础。 不幸的是，它无法扩展，并且受到部落主义（群体内）偏见的影响。


法治:: 建立由机构强制执行的交互规则。 这可以更好地扩展，但由于习俗和传统的差异以及无法扩展执法机构，它无法在全球范围内扩展。 这种解决方案有一个令人讨厌的副作用，即随着机构的扩大，机构变得越来越强大，很可能导致腐败。


信任三方机构:: 在每一次互动中都引入一个中介机构以确保公平。结合“法治”对中介机构进行监督，这种方式规模更大，但同样存在权力不平衡：中介机构变得非常强大，可能会招来腐败。权力集中会导致系统性风险和系统性失败（“大而不能倒”）。


基于博弈论的公平协议::  最后一类来自互联网和密码学的结合，是本节的主题。 让我们看看它是如何工作的，以及它的优点和缺点是什么。

==== 无中间人的信任协议


((("fairness protocol","trusted protocols without intermediaries")))像比特币和闪电网络这样的加密系统是允许你与你不信任的人（包括计算机）进行交易的系统。这通常被称为“免信任”操作，即使它实际上并不是无信任的。 毕竟，您必须信任您运行的软件，并且您必须相信该软件实现的协议将产生公平的结果。


像这样的加密系统与传统金融系统之间的最大区别在于，在传统金融中，您有一个“受信任的第三方”，例如银行，以确保结果是公平的。 此类系统的一个重要问题是它们向第三方提供了过多的权力，而且它们也容易受到“单点故障”的影响。 如果受信任的第三方本身违反信任或试图作弊，信任的基础就会破裂。


当你研究密码系统时，你会注意到一个特定的模式：这些系统不依赖受信任的第三方，而是试图通过使用激励和抑制系统来防止不公平的结果。 在密码系统中，您只需要信任 ((("protocol, defined")))_protocol_，它实际上是一个具有一组规则的系统。如果protocol设计得当，将正确应用所需的激励和抑制。 这种方法的优点是双重的：您不仅可以避免信任第三方，还可以减少您获取公平结果必须付出的努力。 只要参与者遵循商定的协议并留在系统内，该协议中的激励机制就可以在不强制执行的情况下实现公平的结果。


((("game theory")))使用激励机制和抑制机制来实现公平结果是数学分支的一个方面，这被称为博弈论。它研究“理性决策者之间的战略互动模型”footnote:[The Wikipedia https://en.wikipedia.org/wiki/Game_theory[entry on game theory] provides more information.]。控制参与者之间财务互动的密码系统(例如比特币和闪电网络)，严重依赖博弈论来防止参与者作弊，并允许互不信任的参与者获得公平的结果。


虽然博弈论及其在密码系统中的使用，一开始可能看起来令人困惑和陌生，但您很可能在日常生活中早已熟悉这些系统； 你只是没有感知到他们罢了。 在接下来的部分，我们将使用童年时期的一个简单示例，来帮助我们识别博弈论的基本模式。 一旦你了解了基本模式，你会在区块链系统中随处看到它，同时也会快速直观地识别它。


((("fairness protocol", id="ix_01_introduction-asciidoc2", range="startofrange"))) 在本书中，我们将这种模式称为 ((("fairness protocol","defined")))_fairness protocol_，他是指使用激励和(或)抑制系统，来确保彼此无信任的参与者获得公平结果的过程。公平协议的执行只需要确保参与者无法逃避激励或抑制。


==== 现实中的公平协议


((("fairness protocol","real-world example")))让我们看一个您可能已经熟悉的公平协议示例。


想象一下家庭午餐，有父母和两个孩子。孩子们挑食，他们唯一同意吃的就是炸土豆。家长准备了一碗炸土豆（“炸薯条”或“薯条”，取决于您使用的英语方言）。 两个兄弟姐妹必须共享筹码盘。 家长必须确保将筹码公平分配给每个孩子； 否则，父母将听到不断的抱怨（可能整天），并且总是有可能将不公平的情况升级为暴力。父母该做什么？


在两个互不信任且利益冲突的兄弟姐妹之间的这种战略互动中，有几种不同的方式可以实现公平。粗暴且常用的方法是让父母使用他们作为受信任第三方的权威：他们将一碗薯片分成两份，这类似于传统金融。在这个系统中，银行、会计师或律师充当受信任的第三方，以防止想要进行交易的两方之间，出现任何欺诈行为。


这种情况的问题在于它将大量的权力和责任赋予了受信任的第三方手中。 在这个例子中，父母对筹码的平等分配负全部责任，各方只是等待、观察和抱怨。 孩子们指责家长玩偏爱，不公平分配筹码。 兄弟姐妹争着筹码，大喊“那个筹码更大！” 并将父母拖入他们的战斗。 听起来很糟糕，不是吗？ 父母应该大声喊叫吗？ 把所有的筹码都拿走？ 威胁不再做薯条，让那些忘恩负义的孩子挨饿？


存在一个更好的解决方案：教兄弟姐妹玩一种叫做“拆分和选择”的游戏。 每次午餐时，一个兄弟姐妹将一碗薯片分成两份，另一个兄弟姐妹可以选择他们想要的份量。与此同时，让兄弟姐妹弄清楚了这场游戏的动态性，即如果一个“拆分”犯了错误或试图作弊，另一个兄弟姐妹可以通过选择更大的碗来“惩罚”他们。 公平竞争符合兄弟姐妹的最大利益，尤其是分盘者。 在这种情况下，只有作弊者会输。父母甚至不必使用他们的权力或强制执行公平。 父母所要做的就是 _执行协议_ ； 只要兄弟姐妹不能逃避分配给他们的“拆分者”和“选择者”角色，协议本身就可以确保公平的结果，而无需任何干预。父母不能玩最爱或扭曲结果。


[WARNING]
====
虽然 1980 年代臭名昭著的筹码大战清楚地说明了这一点，但前面的场景与作者和他表亲的任何实际童年经历之间的任何相似之处都完全是巧合……或者是这样吗？
====



==== 构建区块的安全原语


((("fairness protocol","security primitives as building blocks")))((("security primitives")))为了使这样的公平协议起作用，需要一些安全原语，可以将它们组合起来以确保执行。第一个安全原语是严格的时间序列：“拆分”动作必须发生在“选择”动作之前。这不是很明显，但除非你能保证动作 A 在动作 B 之前发生，否则协议就会崩溃。第二个安全原语是具有不可否认性的承诺。 每个兄弟姐妹都必须承诺他们选择的角色：拆分者或选择者。 此外，一旦拆分完成，拆分器将致力于他们创建的拆分，他们无法拒绝该选择并再次尝试。


密码系统提供了许多安全原语，它们可以以不同的方式组合以构建公平协议。 除了排序和承诺，我们还可以使用许多其他工具：


- 指纹数据的哈希函数，作为一种承诺形式或作为数字签名的基础
- 用于身份验证、不可否认性和秘密所有权证明的数字签名
- 加密/解密，以限制仅授权参与者访问信息


以上这些，只是正在使用的安全和密码原语的整个“家族”的一小部分。更基本的原语和组合一直在发明。


在我们的实际示例中，我们看到了一种称为“拆分和选择”的公平协议形式。我们可以通过不同的方式来组合安全原语，并构建无数种公平协议。上述示例只是其中一种而已。但基本模式始终是相同的：两个或多个参与者在不相互信任的情况下通过参与一系列协议的步骤进行交互。该协议的步骤，通过激励和抑制措施，以确保：如果参与者是理性的，则作弊会适得其反，而公平是自动的结果。 强制执行不是获得公平结果的必要条件——只需要防止参与者违反商定的协议。


现在您了解了这种基本模式。您将在比特币、闪电网络和许多其他系统中随处看到它。 接下来让我们看一些具体的例子。


==== 公平协议示例


((("fairness protocol","Proof of Work example")))((("PoW (Proof of Work) algorithm")))((("Proof of Work (PoW) algorithm")))公平协议最突出的例子是比特币的共识算法，工作证明（PoW）。在比特币中，矿工竞争验证交易并将它们聚合成块。为了确保矿工在没有授权的情况下不作弊，比特币使用了激励和抑制系统。矿工必须使用电力和专门的硬件来做“工作”，作为嵌入每个区块的“证明”。这是因为散列函数的一个特性而实现的，其中输出值随机分布在整个可能的输出范围内。如果矿工以足够快的速度成功生成有效区块，他们将通过获得该区块的区块奖励来获得奖励。强迫矿工在网络考虑他们的区块之前使用大量电力意味着他们有动力正确验证区块中的交易。如果他们作弊或犯了任何错误，他们的区块就会被拒绝，他们用来“证明”区块的电力就会被浪费掉。没有人需要强迫矿工生产有效区块；奖励和惩罚机制激励他们这样做。协议需要做的就是确保只接受具有工作证明的有效块。


公平协议模型也可以在闪电网络的许多不同方面找到：


* 质押通道的人确保在发布质押交易之前签署了退款交易。


* 每当通道切换到新状态时，旧状态会被“撤销”，以确保如果有人尝试广播它，他们就会失去全部余额并受到惩罚。


* 转发付款的人，如果他们将资金转发出去，他们可以得到退款，也可以通过他们之前的节点获得付款。


我们一次又一次地看到这种模式：公平结果的获得不依赖任何权威机构的强制执行。 它们是奖励公平和惩罚作弊的协议的自然结果，这是一种通过自身利益最大化来做结果导向的公平协议。


比特币和闪电网络都是公平协议的实现。 那么为什么我们需要闪电网络呢？ 比特币还不够吗？


=== 闪电网络的初衷


((("Lightning Network (generally)","motivation for", id="ix_01_introduction-asciidoc3", range="startofrange")))比特币是一个在全球复制的公共分类账上记录交易的系统。 每台参与的计算机都可以查看、验证和存储每笔交易。可以想象，这会产生大量数据并且难以扩展。


随着比特币和交易需求的增长，每个区块中的交易数量不断增加，直到最终达到区块大小限制。一旦块“满了”，多余的交易就会在队列中等待。 许多用户会增加他们愿意为下一个区块的交易购买空间而支付的费用。


如果需求继续超过网络容量，则越来越多的用户交易等待未确认。 费用竞争也增加了每笔交易的成本，使得许多小额交易（例如微交易）在需求特别高的时期完全不经济。


为了解决这个问题，我们可以增加块大小限制，为更多交易创造空间。 区块空间“供应”的增加将导致交易费用的价格均衡降低。


然而，增加区块大小会将成本转移到节点运营商身上，并要求他们花费更多资源来验证和存储区块链。 因为区块链是八卦协议，所以每个节点都需要知道和验证网络上发生的每一笔交易。 此外，一旦经过验证，每个事务和块都必须传播到节点的“邻居”，从而增加带宽需求。 因此，块大小越大，每个单独节点的带宽、处理和存储需求就越大。 以这种方式增加交易容量具有通过减少节点和节点运营商的数量来集中系统的不良效果。 由于节点运营商没有对运行节点进行补偿，如果节点运行成本非常高，那么只有少数资金充足的节点运营商会继续运行节点。


==== 区块链的可扩展性


((("blockchain","scaling", id="ix_01_introduction-asciidoc4", range="startofrange")))((("Lightning Network (generally)","scaling blockchains", id="ix_01_introduction-asciidoc5", range="startofrange")))正如一些数字所显示的那样，增加块大小或减少块时间相对于网络中心化的副作用是严重的。


让我们假设比特币的使用量不断增长，以至于网络必须每秒处理 40,000 笔交易，这是 Visa 网络在高峰使用期间的大致交易处理水平。


假设每个交易平均 250 字节，这将导致每秒 10 兆字节 (MBps) 或每秒 80 兆比特 (Mbps) 的数据流能够接收所有交易。这不包括将交易信息转发给其他对等方的流量开销。虽然在高速光纤和5G移动速度的背景下，10MBps似乎并不极端，但它可以有效地将无法满足此要求的任何人排除在运行节点之外，尤其是在高性能互联网无法负担或无法广泛使用的国家/地区 .


用户对他们的带宽还有许多其他需求，不能指望仅仅为了接收交易而花费这么多。


此外，在本地存储这些信息将导致每天864GB。这大约是1TB的数据，或硬盘驱动器的大小。


每秒验证 40,000 个椭圆曲线数字签名算法 (ECDSA) 签名也几乎不可行(参阅  https://bitcoin.stackexchange.com/questions/95339/how-many-bitcoin-transactions-can-be-verified-per-second[这篇关于 StackExchange 的文章]），如果没有非常昂贵的硬件，比特币区块链的初始块下载（IBD）（同步和验证从创世块开始的所有内容）几乎是不可能的。


虽然每秒 40,000 笔交易似乎很多，但它只能在高峰时段与传统的金融支付网络相提并论。 机器对机器支付、微交易和其他应用程序的创新可能会将需求推向更高的TPS。


简而言之：你无法扩展区块链来以去中心化的方式验证所有的交易。


_但是如果每个节点都不需要知道和验证每一笔交易呢？ 如果有一种方法可以在不失去比特币网络安全性的情况下进行可扩展的链下交易怎么办？_


2015 年 2 月，Joseph Poon 和 Thaddeus Dryja 提出了比特币可扩展性问题的可能解决方案，并发表了“比特币闪电网络：可扩展的链下即时支付”。"footnote:[Joseph Poon and Thaddeus Dryja. "The Bitcoin Lightning Network: Scalable Off-Chain Instant Payments." DRAFT Version 0.5.9.2. January 14, 2016. https://lightning.network/lightning-network-paper.pdf[].]


在（现已过时的）白皮书中，Poon 和 Dryja 估计，为了使比特币达到 Visa 在峰值时每秒处理的 47,000 笔交易，它需要 8 GB 块。
这将使除了大型企业和工业级运营之外的任何人都无法运行节点。
结果将是一个只有少数用户可以实际验证账本状态的网络。
比特币依靠用户自己验证账本，而不明确信任第三方，以保持去中心化。
将用户从正在运行的节点中定价会迫使普通用户信任第三方来发现账本的状态，最终破坏比特币的信任模型。



闪电网络提出了一个新的网络，即二层。用户可以在其中进行点对点支付，而无需为每次支付向比特币区块链发布交易。
用户可以根据需要在闪电网络上多次相互支付，而无需创建额外的比特币交易或产生链上费用。
他们最初只是利用比特币区块链将比特币加载到闪电网络上并“结算”，即从闪电网络中移除比特币。
结果是更多的比特币支付可以在链下进行，只有初始加载和最终结算交易需要由比特币节点验证和存储。
除了减轻节点负担外，闪电网络上的支付对用户来说更便宜，因为他们不需要支付区块链费用，对用户来说更私密，因为它们不会发布给网络的所有参与者，而且不会永久存储。



虽然闪电网络最初是为比特币设计的，但它可以在任何满足一些基本技术要求的区块链上实施。 其他区块链，例如莱特币，已经支持闪电网络。 此外，其他几个区块链正在开发类似的第二层或“第二层”解决方案，以帮助它们扩展。


=== 闪电网络的定义特征



((("Lightning Network (generally)","defining features")))闪电网络是一个在比特币和其他区块链之上作为二层协议运行的网络。闪电网络支持快速、安全、私密、无需信任和无需许可的支付。以下是闪电网络的一些功能：


 
 * 闪电网络的用户可以以低成本和实时的方式相互进行支付。
 

 * 通过闪电网络交换价值的用户无需等待区块确认付款。
 

 * 一旦闪电网络上的付款完成，通常在几秒钟内，它就是最终的，不能撤销。 与比特币交易一样，闪电网络上的付款只能由收款人退还。
 

 * 链上比特币交易由网络中的所有节点广播和验证，而在闪电网络上路由的支付是在成对的节点之间传输的，并且对每个人都不可见，从而产生更大的隐私。
 

 * 与比特币网络上的交易不同，闪电网络上的支付不需要永久存储。 因此，闪电网络使用的资源更少，因此更便宜。此属性还具有保护隐私的好处。
 

 * 闪电网络使用洋葱路由，类似于洋葱路由 (Tor) 隐私网络使用的协议，因此即使参与路由支付的节点也只能直接知道其在支付路由中的前任和后继。
 

* 当在比特币之上使用时，闪电网络使用真正的比特币，它始终由用户拥有（保管）和完全控制。 闪电不是一个单独的代币或硬币，它是比特币。

=== 闪电网络用例、用户和他们的故事


((("Lightning Network (generally)","use cases and users")))为了更好地了解闪电网络的实际工作原理以及人们使用它的原因，我们将关注一些用户及其故事。


在我们的示例中，一些人已经使用过比特币，而另一些人对比特币网络完全陌生。 此处列出的每个人和他们的故事都说明了一个或多个特定用例。 我们将在本书中重新审视它们：



消费者::
Alice 是一位比特币用户，她希望为小额零售购买进行快速、安全、廉价和私密的支付。 她使用闪电网络用比特币购买咖啡。



商户::
Bob 拥有一家咖啡店“Bob's Cafe”。 链上比特币支付不会像一杯咖啡那样小额支付，因此他使用闪电网络几乎可以立即以低廉的费用接受比特币支付。



软件服务商::
Chan 是一位中国企业家，他销售与闪电网络相关的信息服务，以及比特币和其他加密货币。 Chan 通过闪电网络实施小额支付，在互联网上销售这些信息服务。 此外，Chan 实施了一项流动性提供者服务，在闪电网络上租用入站通道容量，每个租期收取少量比特币费用。



游戏玩家::
Dina 是来自俄罗斯的青少年游戏玩家。 她玩过许多不同的电脑游戏，但她最喜欢的是那些有基于真钱的“游戏内经济”的游戏。 在玩游戏时，她还通过购买和销售虚拟游戏内物品来赚钱。 闪电网络允许她为游戏内物品进行少量交易，并为完成任务赚取少量收入。



=== 总结



在本章中，我们讨论了比特币和闪电网络的基本概念：公平协议。




我们研究了闪电网络的历史，也研究了比特币和其他基于区块链网络的二层扩展解决方案背后的动机。


我们学习了基本术语，包括节点、支付渠道、链上交易和链下支付。



最后，我们遇到了 Alice、Bob、Chan 和 Dina，我们将在本书的其余部分中一直关注他们。(((range="endofrange", startref="ix_01_introduction-asciidoc0"))) 在下一章中， 我们将与 Alice 见面，并在她选择闪电钱包并准备进行她的第一次闪电支付以从 Bob's Cafe 购买一杯咖啡时，了解她的思考过程。
